
osx_image: xcode8.2
language: objective-c # 决定构建工具
xcode_project: Example/AiLiToolbox.xcworkspace
xcode_scheme: AiLiToolbox-Example

xcode_sdk: iphonesimulator10.2
podfile: Example/Podfile

branches:
  only:
  - master

before_install:
  - gem install cocoapods --pre