
osx_image: xcode8.2
language: objective-c # 决定构建工具
podfile: Example/Podfile
cache: cocoapods

branches:
  only:
  - master

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=Example/AiLiToolbox.xcworkspace
  matrix:
    - SCHEME="AiLiToolbox-Example"
  before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem uninstall cocoapods -a
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=Example
  script:
  - set -o pipefail
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - pod lib lint --no-clean
  after_success:
  - sleep 5