language: swift # or objective-c
osx_image: xcode7
branches:
  only:
  - master
env:
global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8

  - SCHEME="AiLiToolbox-Example"
  - WORKSPACE=Example/AiLiToolbox.xcworkspace
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods -v 1.2.0 --no-rdoc --no-ri --no-document --quiet
  - pod repo update
  - pod install --project-directory=Example
script:
  - xcodebuild -scheme "$SCHEME" -workspace "$WORKSPACE" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.2,name=iPhone 6S' build test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)